### ISSUE TITLE
Поддержка emoncms

### ISSUE THREAD

**Issue by ale26** [yuri-afanasiev/sonoff-pow-r2#1]
Сейчас у себя пользуюсь системой emoncms (https://emoncms.org/) и есть несколько устройств с прошивкой из этого репозитория.

Хочу подключить sonoff-pow-r2 (с прошивкой @yuri-afanasiev ) к emoncms  для этого готов добавить еще одну интеграцию с поддержкой https-клиента.

@yuri-afanasiev есть сложности со сборкой бинарников. Прошу написать мини-инструкцию в wiki как я могу на основе кода собрать бинарники для ESP, чтобы потом прошивать sonoff-pow-r2

При успешной реализации готов внести PullRequest со своими наработками

Спасибо)

**Comment by yuri-afanasiev** [comment]
@ale26 Поддержка emoncms добавлена 
bin файлы актуальной версии системы  [тут](https://github.com/yuri-afanasiev/sonoff-pow-r2/tree/master/build)
Загрузка bin файлов через  [NodeMCU Flasher](https://github.com/nodemcu/nodemcu-flasher/blob/master/Win32/Release/ESP8266Flasher.exe)
Для загрузки нужен USB-переходник USB - UART 

![Emoncms](https://raw.githubusercontent.com/yuri-afanasiev/sonoff-pow-r2/master/doc/img/2.02.jpg)
![Emoncms](https://raw.githubusercontent.com/yuri-afanasiev/sonoff-pow-r2/master/doc/img/2.01.jpg)

**Comment by yuri-afanasiev** [comment]
@ale26 Инструкция по сбору bin файла уже в wiki [Как собрать bin файл](https://github.com/yuri-afanasiev/sonoff-pow-r2/wiki/Как-собрать-bin-файл)
